version: '3.2'
services:
  postgres-primary:
    image: "postgres:17"  # 使用PostgreSQL 17官方镜像
    container_name: postgres-primary  # 容器命名为postgres-primary
    restart: always  # 容器退出时自动重启
    environment:  # 环境变量配置
      POSTGRES_PASSWORD: 123456  # 设置超级用户postgres的密码
      POSTGRES_REPLICATION_USER: repl  # 专门用于复制的用户名
      POSTGRES_REPLICATION_PASSWORD: 123456  # 复制用户的密码
      TZ: Asia/Shanghai  # 设置容器时区
    volumes:  # 数据卷挂载
      - ./primary/data:/var/lib/postgresql/data  # 持久化数据目录
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化SQL脚本
    networks:  # 网络配置
      blogx_network:
        ipv4_address: 10.2.0.2  # 为主库分配固定IP
    ports:
      - "5432:5432"  # 仅允许宿主机访问主库
    command: >  # PostgreSQL启动参数
      -c wal_level=replica  
      -c max_wal_senders=10  
      -c max_replication_slots=10  
      -c listen_addresses='*'  

  postgres-replica:
    image: "postgres:17"  # 同主库版本
    container_name: postgres-replica  # 容器命名
    restart: always
    depends_on: # 依赖关系
      - postgres-primary  # 确保主库先启动
    environment:
      POSTGRES_PASSWORD: 123456  # 从库的postgres用户密码（建议与主库不同）
      TZ: Asia/Shanghai
    volumes:
      - ./replica/data:/var/lib/postgresql/data  # 从库数据目录
    networks:
      blogx_network:
        ipv4_address: 10.2.0.3  # 从库固定IP

    command: >  # 从库特殊配置
      -c hot_standby=on  
      -c primary_conninfo='host=postgres-primary port=5432 user=repl password=123456 application_name=replica1' 
      -c primary_slot_name=replica_slot
      -c max_standby_streaming_delay = 30s
      -c wal_receiver_status_interval = 10s
      -c hot_standby_feedback = on

  es:
    image: "elasticsearch:7.12.0"
    restart: always
    privileged: true
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
    networks:
      blogx_network:
        ipv4_address: 10.2.0.5

networks:  #定义容器连接网络
  blogx_network:  # 自定义网络名称
    driver: bridge  # 使用桥接模式
    ipam:  # IP地址管理
      driver: default
      config:
        - subnet: 10.2.0.0/24  # 定义子网范围