system:
  ip: ""
  port: 8080
  env: dev
  gin_mode: release
log:
  app: blogx_server
  dir: logs
db:
  user: postgres
  password: 123456
  host: 10.211.55.4
  port: 5432
  database: blogx
  debug: false
  source: postgres
db1:
  user: postgres
  password: 123456
  host: 10.211.55.4
  port: 5432
  database: blogx
  debug: false
  source: postgres
es:
  url: http://10.211.55.4:9200
  username:
  password:
jwt:
  expire: 240
  secret: xxx
  issuer: reisen
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 2
site:
  siteInfo:
    title: ""
    enTitle: ""
    slogan: ""
    logo: ""
    beian: ""
    mode: 2
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
    commentLine: 0
qiniu:
  enable: false
  accessKey: Qb-SEUdl17NxVkyWXtZh8LOWcIcVeQvL4Z2eJfHP
  secretKey: I6NDa02Wk5-rWRbiEVB74fH8sGKisTKICRvYhmrf
  bucket: reisenn
  uri: ""
  region: ""
  prefix: ""
  size: 0
  expiry: 0
ai:
  enable: false
  secretKey: ""
  nickname: ""
  avatar: ""
  abstract: ""
qq:
  appID: "32131424"
  appKey: adadwfea
  redirect: http://xxx.xxx
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 3068272040@qq.com
  authCode: swckpzzxifwjdeic
  sendNickname: 铃仙的博客
  ssl: false
  tls: false
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images001
