system:
  ip: ""
  port: 8080
  env: dev
  gin_mode: release
log:
  app: blogx_server
  dir: logs
db:
- user: root
  password: "123456"
  host: 10.211.55.4
  port: 3306
  database: blogx
  debug: false
  source: mysql
- user: root
  password: "123456"
  host: 10.211.55.4
  port: 3307
  database: blogx
  debug: false
  source: mysql
jwt:
  expire: 240
  secret: xxx
  issuer: reisen
redis:
  addr: 10.211.55.4:6379
  password: ""
  db: 2
site:
  siteInfo:
    title: ""
    enTitle: ""
    slogan: ""
    logo: ""
    beian: ""
    mode: 2
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
    commentLine: 4
qiniu:
  enable: false
  accessKey: Qb-SEUdl17NxVkyWXtZh8LOWcIcVeQvL4Z2eJfHP
  secretKey: I6NDa02Wk5-rWRbiEVB74fH8sGKisTKICRvYhmrf
  bucket: reisenn
  uri: ""
  region: ""
  prefix: ""
  size: 0
  expiry: 0
ai:
  enable: false
  secretKey: ""
  nickname: ""
  avatar: ""
  abstract: ""
qq:
  appID: ""
  appKey: ""
  redirect: ""
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 3068272040@qq.com
  authCode: swckpzzxifwjdeic
  sendNickname: 铃仙的博客
  ssl: false
  tls: false
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images001
es:
  url: http://10.211.55.4:9200
  username: ""
  password: ""
  is_https: false
  enable: true
river:
  enable: false
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  source:
  - schema: blogx
    tables:
    - article_models
  rule:
  - schema: blogx
    table: article_models
    index: article_index
    type: _doc
    field:
      tag_list: tags,list
  bulk_size: 128
