system:
  ip:
  port: 8080
  env: dev # 一般用于gin的日志输出
  gin_mode: release

jwt:
  expire: 240 # 过期时间
  secret: xxx # 密钥
  issuer: reisen # 签发人
log:
  app: blogx_server
  dir: logs
redis:
  addr: 127.0.0.1:6379
  password: 1234
  db: 2

db:
  user: root
  password: root
  host: 127.0.0.1
  port: 5432
  database: gvb_db
  debug: false
  source: postgres
# 数据库配置一样，模拟多个数据库读写分离
db1:
  user: root
  password: root
  host: 127.0.0.1
  port: 5432
  database: gvb_db
  debug: false
  source: postgres